[package]
name = "tvp-storages"
description = "Storages native class in Rust: storage queries over mounted game storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tjs2-sys = { workspace = true }
engine = { path = "../engine" }
tvp-util = { path = "../tvp-util" }
log = "0.4"
