[workspace]
resolver = "2"
members = ["crates/xp3", "crates/tjs2-sys", "crates/engine", "crates/kag", "crates/tvp-util", "crates/tvp-streams", "crates/tvp-natives", "crates/tvp-storages", "crates/tvp-scripts", "crates/tvp-archive", "crates/tvp-config", "crates/app", "crates/tvp-visual", "crates/render", "crates/tvp-text", "crates/tvp-kagparser", "crates/tvp-input", "crates/tvp-sound"]
default-members = ["crates/render", "crates/app"]

[workspace.package]
version = "1.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
xp3 = { path = "crates/xp3" }
tjs2-sys = { path = "crates/tjs2-sys" }

[profile.release]
lto = "thin"
strip = "symbols"
codegen-units = 1
